name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.9+1
homepage: https://github.com/appsup-dart/openid_client
repository: https://github.com/appsup-dart/openid_client
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jose: ^0.3.2
  pointycastle: '>=3.0.0 <5.0.0'
  http: ">=0.13.5 <2.0.0"
  logging: ^1.0.0
  args: ^2.0.0
  meta: ^1.0.0
  clock: ^1.1.0
  web: ^1.1.0

dev_dependencies:
  test: ^1.16.5
  lints: ^6.0.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1

executables:
  openid_client: openid_client
