name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.3
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jose: ^0.3.2
  pointycastle: ^3.0.0
  http: ^0.13.0
  logging: ^1.0.0
  args: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.16.5
  pedantic: ^1.11.0

executables:
  openid_client: openid_client