name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.2.0
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: '>=1.21.0 <3.0.0'

dependencies:
  jose: ^0.1.0
  pointycastle: ^1.0.0-rc4
  http: ^0.12.0
  logging: ^0.11.3+2
  args: ^1.5.0

dev_dependencies:
  test: ^1.0.0
  angular: ^5.0.0

executables:
  openid_client: openid_client