name: browser_example
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  path: ^1.7.0
  openid_client: 
    path: ../..
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.0
  lints: ^6.0.0
